language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
before_install:
  - gem install bundler:2.1.4
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: tqThXLxbieLNNT4qsif+H7ye89jMiSyXYi29WB46KDpYP2YtRH8hfCg+jNfypAEn3EKwNwBNqDtn7PlCQunYL2koLnAGRnK0lbkvdvjcqIXT5PHTOeDfPjDsLNe3YGoAVLBbhSLYJvKkN40o/DouOrCo6UnqG2Vv4PakQoOBoF+eR70r9Yg7XaohmkySr+zatXQjBoNB6wfw2UmwOD7sOhB2kmLV0FpwSFOoWfVrsRw5J6/Oa3xyknQQkgLy3XUkU8SG8tl4KwAu5W56ynqq58Z0S9RkeRmTNO4562XLsvd1xiV91dtm6PDTxd6w5bIy3m2vSM2Jt5YhDrqvAHXcB3PV/F+eLyrH/2DtzkxHqLroGkCB/5ZsfbVD3ocSzG9sFTDlsZwqVMqQXhCH/6KiZz6Q+UMDS2UCxNg8hwRxcoz0mdbRPB7u5o0NcMnRLWN/S8Mx7pp5h5M6owDD9qU0yowNvIPxbLIxXW1ki61XJrqH1rb0z3BrYkC7bkD705dfJ91n1mxyfrzcDo/zbxb2/xC6oLTEwuvvIA7jE7YMS5rrFekriGdRQD5WD1KaxMDs9JEpE5gNARFJB/bG5y5iTiDxnjivEKiyr2TIcFlsqsTFxN1fkQJFZ9YjpH2LT0r9YwSpao4kOxFDUh8hgumVj4mxBEKHOXZerdvLOwUD3TE=
  on:
    all_branches: true
  app: desolate-journey-50207
  run: rails db:migrate

